application: webrtcbogbog
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /js
  static_dir: js
- url: /css
  static_dir: css
- url: /.*
  script: webrtcbogbog.app

libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: latest
